# Generated by Django 3.2.7 on 2021-09-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'verbose_name': 'Актриса', 'verbose_name_plural': 'Актрисы'},
        ),
    ]
